Fix: JAXB NoClassDefFoundError on Java 9+ (#218)
JAXB APIs are considered to be a part of Java EE and was removed by default in Java SE 9.
See: https://stackoverflow.com/a/47412779/6238618